import uuid

# Generated by forms/scripts/sync.mjs. Do not edit.
# Stable identifiers for this form -- do not change across versions.
FORM_ID = uuid.UUID("ad4f20f4-87af-5ac1-8ef7-cf7a35e96526")
SHORT_FORM_NAME = "SF424_Short_3_0_Portable"
