import uuid

# Generated by forms/scripts/sync.mjs. Do not edit.
# Stable identifiers for this form -- do not change across versions.
FORM_ID = uuid.UUID("cc8629d5-1ab5-5da2-87a4-214509f8af39")
SHORT_FORM_NAME = "SF424_4_0"
