import uuid

# Generated by forms/scripts/sync.mjs. Do not edit.
# Stable identifiers for this form -- do not change across versions.
FORM_ID = uuid.UUID("191fab38-0885-5cff-9af5-dd07d0289fa5")
SHORT_FORM_NAME = "SF424A_Portable"
