"""Load a versioned form definition from a form directory.

A form version may be declared either as a Python module (``form_json.py``) or as a
JSON document (``form.json``). Both produce a module exposing the same attributes, so
each form package's ``__init__.py`` reads the same way regardless of which format its
version directory uses.

The JSON format exists so that forms generated by an external toolchain can be committed
directly, without a Python file whose only job is to hold literals.
"""

import dataclasses
import importlib.util
import json
import types
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

from src.constants.lookup_constants import FormType
from src.db.models.competition_models import Form

PYTHON_FORM_FILENAME = "form_json.py"
JSON_FORM_FILENAME = "form.json"

# Ordered so error messages list the long-standing format first.
FORM_SOURCE_FILENAMES = (PYTHON_FORM_FILENAME, JSON_FORM_FILENAME)

# Populated at runtime by the get_form service, so a form never declares it.
_JSON_EXCLUDED_FIELDS = frozenset({"form_instruction"})

_UUID_FIELDS = frozenset({"form_id", "form_instruction_id"})
_DATETIME_FIELDS = frozenset({"active_at", "inactive_at"})

# The attributes a form_json.py module exposes, mapped to the Form field each one holds.
# The JSON loader mirrors these so both formats present an identical module surface.
_SCHEMA_ATTRIBUTES = {
    "FORM_JSON_SCHEMA": "form_json_schema",
    "FORM_UI_SCHEMA": "form_ui_schema",
    "FORM_RULE_SCHEMA": "form_rule_schema",
    "FORM_XML_TRANSFORM_RULES": "json_to_xml_schema",
}


def find_form_source(version_dir: Path) -> Path:
    """Return the single form definition file in a version directory.

    Raises if the directory holds neither file, or both — a version that declares itself
    twice has no unambiguous definition, and silently preferring one would let the other
    drift unnoticed.
    """
    present = [
        version_dir / name for name in FORM_SOURCE_FILENAMES if (version_dir / name).exists()
    ]

    if not present:
        expected = " or ".join(FORM_SOURCE_FILENAMES)
        raise FileNotFoundError(f"No {expected} found in {version_dir}")
    if len(present) > 1:
        names = ", ".join(p.name for p in present)
        raise ValueError(f"{version_dir} contains {names}; a version must declare exactly one")

    return present[0]


def build_form_from_dict(data: dict[str, Any], source: Path) -> Form:
    """Construct a Form from decoded JSON, coercing the fields JSON cannot represent."""
    allowed = {f.name for f in dataclasses.fields(Form)} - _JSON_EXCLUDED_FIELDS

    unknown = sorted(set(data) - allowed)
    if unknown:
        raise ValueError(
            f"{source}: unknown field(s): {', '.join(unknown)}. "
            f"Allowed fields: {', '.join(sorted(allowed))}"
        )

    kwargs = dict(data)

    for field in _UUID_FIELDS:
        value = kwargs.get(field)
        if isinstance(value, str):
            try:
                kwargs[field] = uuid.UUID(value)
            except ValueError as err:
                raise ValueError(f"{source}: {field} is not a valid UUID: {value!r}") from err

    for field in _DATETIME_FIELDS:
        value = kwargs.get(field)
        if isinstance(value, str):
            try:
                kwargs[field] = datetime.fromisoformat(value)
            except ValueError as err:
                raise ValueError(
                    f"{source}: {field} is not a valid ISO 8601 datetime: {value!r}"
                ) from err

    form_type = kwargs.get("form_type")
    if isinstance(form_type, str):
        try:
            kwargs["form_type"] = FormType(form_type)
        except ValueError as err:
            valid = ", ".join(t.value for t in FormType)
            raise ValueError(
                f"{source}: form_type {form_type!r} is not a known FormType. Valid values: {valid}"
            ) from err

    try:
        return Form(**kwargs)
    except TypeError as err:
        raise ValueError(f"{source}: {err}") from err


def _load_json_form(form_path: Path, module_name: str) -> types.ModuleType:
    """Build a module from a form.json, exposing the same attributes as a form_json.py."""
    try:
        data = json.loads(form_path.read_text())
    except json.JSONDecodeError as err:
        raise ValueError(f"{form_path}: invalid JSON: {err}") from err

    if not isinstance(data, dict):
        raise ValueError(f"{form_path}: expected a JSON object at the top level")

    form = build_form_from_dict(data, form_path)

    # The full module surface, assembled in one place so it is legible next to the
    # form_json.py it stands in for. A JSON-declared form is reached as FORM; a
    # Python-declared form is reached by whatever variable its module happens to name,
    # which is why each form package's __init__.py aliases it.
    surface: dict[str, Any] = {"FORM": form}
    surface.update({a: getattr(form, f) for a, f in _SCHEMA_ATTRIBUTES.items()})

    module = types.ModuleType(module_name)
    module.__file__ = str(form_path)
    for attribute, value in surface.items():
        setattr(module, attribute, value)

    return module


def _load_python_form(form_path: Path, module_name: str) -> types.ModuleType:
    spec = importlib.util.spec_from_file_location(module_name, form_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load form module from {form_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_versioned_form(path: Path, version: str) -> types.ModuleType:
    """Load the form definition for a version, from either supported format."""
    major, minor = version.split(".")
    version_dir = path / major / minor
    module_name = f"{path.name}._v{major}_{minor}"

    form_path = find_form_source(version_dir)

    if form_path.name == JSON_FORM_FILENAME:
        return _load_json_form(form_path, module_name)
    return _load_python_form(form_path, module_name)
