"""Load a versioned form definition from a form directory.

A form version may be declared either as a Python module (``form_json.py``) or as a
JSON document (``form.json``). Both produce a module exposing the same attributes, so
each form package's ``__init__.py`` reads the same way regardless of which format its
version directory uses.

The JSON format exists so that forms generated by an external toolchain can be committed
directly, without a Python file whose only job is to hold literals.

A form.json may keep its four large documents -- the JSON schema, UI schema, rule schema
and XML transform -- in sibling schema files rather than inline, which is what the generated
forms do: a change to one of them then shows up as a diff in that file alone instead of inside
a single document many thousands of lines long. Each schema file is optional and is folded
into the form.json on load, so a fully inline form.json is still valid.
"""

import dataclasses
import importlib.util
import json
import types
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, NamedTuple

from src.constants.lookup_constants import FormType
from src.db.models.competition_models import Form

PYTHON_FORM_FILENAME = "form_json.py"
JSON_FORM_FILENAME = "form.json"

# Ordered so error messages list the long-standing format first.
FORM_SOURCE_FILENAMES = (PYTHON_FORM_FILENAME, JSON_FORM_FILENAME)

# Populated at runtime by the get_form service, so a form never declares it.
_JSON_EXCLUDED_FIELDS = frozenset({"form_instruction"})

_UUID_FIELDS = frozenset({"form_id", "form_instruction_id"})
_DATETIME_FIELDS = frozenset({"active_at", "inactive_at"})


class _SchemaDocument(NamedTuple):
    """The two names one of the large form documents goes by outside the Form itself."""

    attribute: str  # what a form_json.py module exposes it as
    filename: str  # the sibling file a form.json may hold it in instead of inline


# The four large documents, keyed by the Form field each one fills. Both of the names a
# document goes by live in the same row, so the attribute surface and the schema files
# cannot drift apart: adding a document here gives it both, or neither.
#
# The attributes are what a form_json.py declares; the JSON loader mirrors them so both
# formats present an identical module surface. The schema files are optional -- splitting a
# document out of the form.json keeps a change to it out of the other documents' diffs, and
# a form.json that declares everything inline still loads unchanged.
_SCHEMA_DOCUMENTS = {
    "form_json_schema": _SchemaDocument("FORM_JSON_SCHEMA", "json_schema.json"),
    "form_ui_schema": _SchemaDocument("FORM_UI_SCHEMA", "ui_schema.json"),
    "form_rule_schema": _SchemaDocument("FORM_RULE_SCHEMA", "rule_schema.json"),
    "json_to_xml_schema": _SchemaDocument("FORM_XML_TRANSFORM_RULES", "xml_transform.json"),
}


def find_form_source(version_dir: Path) -> Path:
    """Return the single form definition file in a version directory.

    Raises if the directory holds neither file, or both — a version that declares itself
    twice has no unambiguous definition, and silently preferring one would let the other
    drift unnoticed.
    """
    present = [
        version_dir / name for name in FORM_SOURCE_FILENAMES if (version_dir / name).exists()
    ]

    if not present:
        expected = " or ".join(FORM_SOURCE_FILENAMES)
        raise FileNotFoundError(f"No {expected} found in {version_dir}")
    if len(present) > 1:
        names = ", ".join(p.name for p in present)
        raise ValueError(f"{version_dir} contains {names}; a version must declare exactly one")

    return present[0]


def build_form_from_dict(data: dict[str, Any], source: Path) -> Form:
    """Construct a Form from decoded JSON, coercing the fields JSON cannot represent."""
    allowed = {f.name for f in dataclasses.fields(Form)} - _JSON_EXCLUDED_FIELDS

    unknown = sorted(set(data) - allowed)
    if unknown:
        raise ValueError(
            f"{source}: unknown field(s): {', '.join(unknown)}. "
            f"Allowed fields: {', '.join(sorted(allowed))}"
        )

    kwargs = dict(data)

    for field in _UUID_FIELDS:
        value = kwargs.get(field)
        if isinstance(value, str):
            try:
                kwargs[field] = uuid.UUID(value)
            except ValueError as err:
                raise ValueError(f"{source}: {field} is not a valid UUID: {value!r}") from err

    for field in _DATETIME_FIELDS:
        value = kwargs.get(field)
        if isinstance(value, str):
            try:
                kwargs[field] = datetime.fromisoformat(value)
            except ValueError as err:
                raise ValueError(
                    f"{source}: {field} is not a valid ISO 8601 datetime: {value!r}"
                ) from err

    form_type = kwargs.get("form_type")
    if isinstance(form_type, str):
        try:
            kwargs["form_type"] = FormType(form_type)
        except ValueError as err:
            valid = ", ".join(t.value for t in FormType)
            raise ValueError(
                f"{source}: form_type {form_type!r} is not a known FormType. Valid values: {valid}"
            ) from err

    try:
        return Form(**kwargs)
    except TypeError as err:
        raise ValueError(f"{source}: {err}") from err


def _read_json(path: Path) -> Any:
    """Decode a JSON document, naming the file in the error when it will not parse."""
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as err:
        raise ValueError(f"{path}: invalid JSON: {err}") from err


def _merge_schema_files(data: dict[str, Any], version_dir: Path) -> dict[str, Any]:
    """Fold each sibling schema file present into the decoded form.json.

    A field declared both inline and in its schema file is an error rather than a precedence
    rule: the two would drift, and silently preferring one hides that the other is stale.
    """
    merged = dict(data)

    for field, document in _SCHEMA_DOCUMENTS.items():
        path = version_dir / document.filename
        if not path.exists():
            continue
        if field in merged:
            raise ValueError(
                f"{path}: {field} is declared both inline in {JSON_FORM_FILENAME} and in "
                f"{document.filename}; a field must be declared exactly once"
            )
        merged[field] = _read_json(path)

    return merged


def _load_json_form(form_path: Path, module_name: str) -> types.ModuleType:
    """Build a module from a form.json, exposing the same attributes as a form_json.py."""
    data = _read_json(form_path)

    if not isinstance(data, dict):
        raise ValueError(f"{form_path}: expected a JSON object at the top level")

    data = _merge_schema_files(data, form_path.parent)

    form = build_form_from_dict(data, form_path)

    # The full module surface, assembled in one place so it is legible next to the
    # form_json.py it stands in for. A JSON-declared form is reached as FORM; a
    # Python-declared form is reached by whatever variable its module happens to name,
    # which is why each form package's __init__.py aliases it.
    surface: dict[str, Any] = {"FORM": form}
    surface.update({d.attribute: getattr(form, f) for f, d in _SCHEMA_DOCUMENTS.items()})

    module = types.ModuleType(module_name)
    module.__file__ = str(form_path)
    for attribute, value in surface.items():
        setattr(module, attribute, value)

    return module


def _load_python_form(form_path: Path, module_name: str) -> types.ModuleType:
    spec = importlib.util.spec_from_file_location(module_name, form_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load form module from {form_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_versioned_form(path: Path, version: str) -> types.ModuleType:
    """Load the form definition for a version, from either supported format."""
    major, minor = version.split(".")
    version_dir = path / major / minor
    module_name = f"{path.name}._v{major}_{minor}"

    form_path = find_form_source(version_dir)

    if form_path.name == JSON_FORM_FILENAME:
        return _load_json_form(form_path, module_name)
    return _load_python_form(form_path, module_name)
