import uuid

# Generated by forms/scripts/sync.mjs. Do not edit.
# Stable identifiers for this form -- do not change across versions.
FORM_ID = uuid.UUID("9bffc60c-ded2-522c-b986-bd5f9bbb1036")
SHORT_FORM_NAME = "RR_KeyPersonExpanded_4_0_Portable"
