import uuid

# Generated by forms/scripts/sync.mjs. Do not edit.
# Stable identifiers for this form -- do not change across versions.
FORM_ID = uuid.UUID("557f45e4-92b6-5d1e-9ae0-62cd3aad8c58")
SHORT_FORM_NAME = "EPA_KeyContacts_Portable"
