import uuid

# Generated by forms/scripts/sync.mjs. Do not edit.
# Stable identifiers for this form -- do not change across versions.
FORM_ID = uuid.UUID("051d808e-62d7-58a4-933d-38c54652f1fe")
SHORT_FORM_NAME = "Key_Contacts"
